# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# db/seeds.rb

Product.create([
  {
    name: "Elica 60 cm 1350 m3/hr Filterless Autoclean Kitchen Chimney",
    description: "Filterless technology ensures powerful suction and easy cleaning.",
    category: "Home Appliances",
    subcategory: "Kitchen Chimney",
    tags: ["chimney", "filterless", "kitchen"],
    rating: 4.5,
    reviews_count: 11486,
    bought_in_past_month: 200,
    price: 20000,
    discount_price: 13500,
    free_delivery: true,
    stock: 10,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "2-3 Days",
    image_url: "elica_chimney.jpg",
    thumbnail_url: "elica_chimney_thumb.jpg",
    video_url: "elica_chimney_video.mp4",
    brand: "Elica",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 101,
    is_featured: true,
  },
  {
    name: "Panasonic 6 Kg 4 Star Fully-Automatic Top Load Washing Machine",
    description: "4-star rated washing machine with powerful motor and sleek design.",
    category: "Home Appliances",
    subcategory: "Washing Machine",
    tags: ["washing machine", "automatic", "panasonic"],
    rating: 4.3,
    reviews_count: 7131,
    bought_in_past_month: 400,
    price: 20000,
    discount_price: 13990,
    free_delivery: true,
    stock: 8,
    unit: "6 Kg",
    availability_status: true,
    delivery_time: "1-2 Days",
    image_url: "panasonic_washing_machine.jpg",
    thumbnail_url: "panasonic_washing_machine_thumb.jpg",
    video_url: "panasonic_washing_machine_video.mp4",
    brand: "Panasonic",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 102,
    is_featured: false,
  },
  {
    name: "Sony Bravia 55 inches 4K Ultra HD Smart LED TV",
    description: "Immersive 4K Ultra HD experience with smart features.",
    category: "Electronics",
    subcategory: "Television",
    tags: ["tv", "smart tv", "sony"],
    rating: 4.6,
    reviews_count: 8790,
    bought_in_past_month: 120,
    price: 75000,
    discount_price: 68999,
    free_delivery: true,
    stock: 5,
    unit: "55 inches",
    availability_status: true,
    delivery_time: "2-4 Days",
    image_url: "sony_bravia_tv.jpg",
    thumbnail_url: "sony_bravia_tv_thumb.jpg",
    video_url: "sony_bravia_tv_video.mp4",
    brand: "Sony",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 103,
    is_featured: true,
  },
  {
    name: "Dell Inspiron 15 5000 Series Laptop i5 processor and 8GB RAM.",
    description: "Powerful laptop with Intel i5 processor and 8GB RAM.",
    category: "Electronics",
    subcategory: "Laptop",
    tags: ["laptop", "dell", "inspiron"],
    rating: 4.2,
    reviews_count: 4523,
    bought_in_past_month: 60,
    price: 60000,
    discount_price: 57999,
    free_delivery: false,
    stock: 12,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "3-5 Days",
    image_url: "dell_inspiron_laptop.jpg",
    thumbnail_url: "dell_inspiron_laptop_thumb.jpg",
    video_url: "dell_inspiron_laptop_video.mp4",
    brand: "Dell",
    product_origin: "Local",
    dietary_info: [],
    seller_id: 104,
    is_featured: false,
  },
  {
    name: "Whirlpool 340 L 3 Star Frost-Free Double Door Refrigerator",
    description: "Spacious refrigerator with efficient cooling technology.",
    category: "Home Appliances",
    subcategory: "Refrigerator",
    tags: ["refrigerator", "double door", "whirlpool"],
    rating: 4.4,
    reviews_count: 3192,
    bought_in_past_month: 85,
    price: 40000,
    discount_price: 37990,
    free_delivery: true,
    stock: 7,
    unit: "340 L",
    availability_status: true,
    delivery_time: "1-2 Days",
    image_url: "whirlpool_refrigerator.jpg",
    thumbnail_url: "whirlpool_refrigerator_thumb.jpg",
    video_url: "whirlpool_refrigerator_video.mp4",
    brand: "Whirlpool",
    product_origin: "Local",
    dietary_info: [],
    seller_id: 105,
    is_featured: true,
  },
  {
    name: "Elica 60 cm 1350 m3/hr Filterless Autoclean Kitchen Chimney",
    description: "Filterless technology ensures powerful suction and easy cleaning.",
    category: "Home Appliances",
    subcategory: "Kitchen Chimney",
    tags: ["chimney", "filterless", "kitchen"],
    rating: 4.5,
    reviews_count: 11486,
    bought_in_past_month: 200,
    price: 20000,
    discount_price: 13500,
    free_delivery: true,
    stock: 10,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "2-3 Days",
    image_url: "elica_chimney.jpg",
    thumbnail_url: "elica_chimney_thumb.jpg",
    video_url: "elica_chimney_video.mp4",
    brand: "Elica",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 101,
    is_featured: true,
  },
  {
    name: "Elica 60 cm 1350 m3/hr Filterless Autoclean Kitchen Chimney",
    description: "Filterless technology ensures powerful suction and easy cleaning.",
    category: "Home Appliances",
    subcategory: "Kitchen Chimney",
    tags: ["chimney", "filterless", "kitchen"],
    rating: 4.5,
    reviews_count: 11486,
    bought_in_past_month: 200,
    price: 20000,
    discount_price: 13500,
    free_delivery: true,
    stock: 10,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "2-3 Days",
    image_url: "elica_chimney.jpg",
    thumbnail_url: "elica_chimney_thumb.jpg",
    video_url: "elica_chimney_video.mp4",
    brand: "Elica",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 101,
    is_featured: true,
  },
  {
    name: "Elica 60 cm 1350 m3/hr Filterless Autoclean Kitchen Chimney",
    description: "Filterless technology ensures powerful suction and easy cleaning.",
    category: "Home Appliances",
    subcategory: "Kitchen Chimney",
    tags: ["chimney", "filterless", "kitchen"],
    rating: 4.5,
    reviews_count: 11486,
    bought_in_past_month: 200,
    price: 20000,
    discount_price: 13500,
    free_delivery: true,
    stock: 10,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "2-3 Days",
    image_url: "elica_chimney.jpg",
    thumbnail_url: "elica_chimney_thumb.jpg",
    video_url: "elica_chimney_video.mp4",
    brand: "Elica",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 101,
    is_featured: true,
  },
  {
    name: "Elica 60 cm 1350 m3/hr Filterless Autoclean Kitchen Chimney",
    description: "Filterless technology ensures powerful suction and easy cleaning.",
    category: "Home Appliances",
    subcategory: "Kitchen Chimney",
    tags: ["chimney", "filterless", "kitchen"],
    rating: 4.5,
    reviews_count: 11486,
    bought_in_past_month: 200,
    price: 20000,
    discount_price: 13500,
    free_delivery: true,
    stock: 10,
    unit: "1 Unit",
    availability_status: true,
    delivery_time: "2-3 Days",
    image_url: "elica_chimney.jpg",
    thumbnail_url: "elica_chimney_thumb.jpg",
    video_url: "elica_chimney_video.mp4",
    brand: "Elica",
    product_origin: "Imported",
    dietary_info: [],
    seller_id: 101,
    is_featured: true,
  },
])
